name = "Dumper"
uuid = "8642fa86-e71c-4b93-8618-293c1d7e5bde"
authors = ["Cursor Insight <info@cursorinsight.com>"]
version = "0.2.3"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
MacroTools = "0.5"
julia = "1.6"
